In [1]:
import numpy as np
import pandas as pd

In [2]:
print(pd.__version__)

2.2.3

In [21]:
my_list = ['apple', 'banana', 'cherry']
ser = pd.Series(my_list)

In [22]:
print(ser)

0     apple
1    banana
2    cherry
dtype: object

In [23]:
ser[-1]

KeyError: -1

In [15]:
my_list = ['apple', 'banana', 'cherry']
ser = pd.Series(my_list, index = ['A', 'B', 'C'])

In [16]:
print(ser)

A     apple
B    banana
C    cherry
dtype: object

In [17]:
ser['A']

'apple'

In [18]:
ser['A': 'C']

A     apple
B    banana
C    cherry
dtype: object

In [20]:
ser[-'C']

TypeError: bad operand type for unary -: 'str'

In [8]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])    
print(ser1)

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [9]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])  
print(ser2)

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [10]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [3]:
# DataFrames
students = {'Roll_no': [101, 102, 103, 104, 105],
           'Name': ['Ali', 'Ahmad', 'Umer', 'Zubair', 'Tayyab'],
           'Subject': ['OOP', 'Database', 'Software Engineering', 'OS', 'Programing'],
           'Marks': [80, 87, 67, 56, 92]}

In [4]:
students

{'Roll_no': [101, 102, 103, 104, 105],
 'Name': ['Ali', 'Ahmad', 'Umer', 'Zubair', 'Tayyab'],
 'Subject': ['OOP', 'Database', 'Software Engineering', 'OS', 'Programing'],
 'Marks': [80, 87, 67, 56, 92]}

In [7]:
df_student = pd.DataFrame(students)

In [8]:
df_student

   Roll_no    Name               Subject  Marks
0      101     Ali                   OOP     80
1      102   Ahmad              Database     87
2      103    Umer  Software Engineering     67
3      104  Zubair                    OS     56
4      105  Tayyab            Programing     92

In [9]:
df_student['Roll_no']

0    101
1    102
2    103
3    104
4    105
Name: Roll_no, dtype: int64

In [10]:
df_student[0]

KeyError: 0

In [15]:
df_student[['Roll_no', 'Name', 'Marks']]

   Roll_no    Name  Marks
0      101     Ali     80
1      102   Ahmad     87
2      103    Umer     67
3      104  Zubair     56
4      105  Tayyab     92

In [16]:
df_student['Percentage'] = df_student['Marks']/200 * 100

In [17]:
df_student

   Roll_no    Name               Subject  Marks  Percentage
0      101     Ali                   OOP     80        40.0
1      102   Ahmad              Database     87        43.5
2      103    Umer  Software Engineering     67        33.5
3      104  Zubair                    OS     56        28.0
4      105  Tayyab            Programing     92        46.0

In [18]:
df_student.drop('Percentage')

KeyError: "['Percentage'] not found in axis"

In [19]:
df_student.drop(1)

   Roll_no    Name               Subject  Marks  Percentage
0      101     Ali                   OOP     80        40.0
2      103    Umer  Software Engineering     67        33.5
3      104  Zubair                    OS     56        28.0
4      105  Tayyab            Programing     92        46.0

In [20]:
df_student.drop('Percentage', axis = 1)

   Roll_no    Name               Subject  Marks
0      101     Ali                   OOP     80
1      102   Ahmad              Database     87
2      103    Umer  Software Engineering     67
3      104  Zubair                    OS     56
4      105  Tayyab            Programing     92

In [21]:
df_student.drop(columns = ['Percentage'])

   Roll_no    Name               Subject  Marks
0      101     Ali                   OOP     80
1      102   Ahmad              Database     87
2      103    Umer  Software Engineering     67
3      104  Zubair                    OS     56
4      105  Tayyab            Programing     92

In [22]:
df_student

   Roll_no    Name               Subject  Marks  Percentage
0      101     Ali                   OOP     80        40.0
1      102   Ahmad              Database     87        43.5
2      103    Umer  Software Engineering     67        33.5
3      104  Zubair                    OS     56        28.0
4      105  Tayyab            Programing     92        46.0

In [35]:
df_update = df_student.drop('Percentage', axis = 1)

In [36]:
df_update

   Roll_no    Name               Subject  Marks
0      101     Ali                   OOP     80
1      102   Ahmad              Database     87
2      103    Umer  Software Engineering     67
3      104  Zubair                    OS     56
4      105  Tayyab            Programing     92

In [37]:
df_student

   Roll_no    Name               Subject  Marks  Percentage
0      101     Ali                   OOP     80        40.0
1      102   Ahmad              Database     87        43.5
2      103    Umer  Software Engineering     67        33.5
3      104  Zubair                    OS     56        28.0
4      105  Tayyab            Programing     92        46.0

In [38]:
df_student.drop('Percentage', axis = 1, inplace=True)

In [39]:
df_student

   Roll_no    Name               Subject  Marks
0      101     Ali                   OOP     80
1      102   Ahmad              Database     87
2      103    Umer  Software Engineering     67
3      104  Zubair                    OS     56
4      105  Tayyab            Programing     92

In [23]:
df_student.drop(columns=['Percentage', 'Marks', 'Name'])

   Roll_no               Subject
0      101                   OOP
1      102              Database
2      103  Software Engineering
3      104                    OS
4      105            Programing

In [24]:
df_student.drop([1, 2, 4])

   Roll_no    Name Subject  Marks  Percentage
0      101     Ali     OOP     80        40.0
3      104  Zubair      OS     56        28.0

In [25]:
df_student.drop([1: 3])

SyntaxError: invalid syntax (2309636950.py, line 1)

In [26]:
df_update2 = df_student.drop([1, 2, 4])

In [27]:
df_update2

   Roll_no    Name Subject  Marks  Percentage
0      101     Ali     OOP     80        40.0
3      104  Zubair      OS     56        28.0

In [31]:
df_update3 = df_update2.reset_index()

In [32]:
df_update3 = df_update3.drop('index', axis = 1)

In [33]:
df_update3

   Roll_no    Name Subject  Marks  Percentage
0      101     Ali     OOP     80        40.0
1      104  Zubair      OS     56        28.0

In [34]:
df_student

   Roll_no    Name               Subject  Marks  Percentage
0      101     Ali                   OOP     80        40.0
1      102   Ahmad              Database     87        43.5
2      103    Umer  Software Engineering     67        33.5
3      104  Zubair                    OS     56        28.0
4      105  Tayyab            Programing     92        46.0

In [35]:
df_student2 = df_student.set_index('Roll_no')

In [36]:
df_student2

           Name               Subject  Marks  Percentage
Roll_no
101         Ali                   OOP     80        40.0
102       Ahmad              Database     87        43.5
103        Umer  Software Engineering     67        33.5
104      Zubair                    OS     56        28.0
105      Tayyab            Programing     92        46.0

In [37]:
df_student2.drop([102, 105])

           Name               Subject  Marks  Percentage
Roll_no
101         Ali                   OOP     80        40.0
103        Umer  Software Engineering     67        33.5
104      Zubair                    OS     56        28.0

In [38]:
df_student2.drop()

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [39]:
# loc[row, col]
# iloc

df_student2.loc[103]

Name                          Umer
Subject       Software Engineering
Marks                           67
Percentage                    33.5
Name: 103, dtype: object

In [40]:
df_student2.loc[103: 105]

           Name               Subject  Marks  Percentage
Roll_no
103        Umer  Software Engineering     67        33.5
104      Zubair                    OS     56        28.0
105      Tayyab            Programing     92        46.0

In [41]:
df_student2.loc[103: 105, 'Marks']

Roll_no
103    67
104    56
105    92
Name: Marks, dtype: int64

In [51]:
df_student2.loc[[103, 105, 102], 'Marks']

Roll_no
103    67
105    92
102    87
Name: Marks, dtype: int64

In [42]:
df_student2.loc[103: 105, ['Subject', 'Marks']]

                      Subject  Marks
Roll_no
103      Software Engineering     67
104                        OS     56
105                Programing     92

In [44]:
df_student2[['Subject', 'Marks']].loc[103: 105]

                      Subject  Marks
Roll_no
103      Software Engineering     67
104                        OS     56
105                Programing     92

In [45]:
df_student2[['Subject', 'Marks']].tail(3)

                      Subject  Marks
Roll_no
103      Software Engineering     67
104                        OS     56
105                Programing     92

In [47]:
df_student2.iloc[1:3, [2, 3]]

         Marks  Percentage
Roll_no
102         87        43.5
103         67        33.5

In [48]:
df_student

   Roll_no    Name               Subject  Marks  Percentage
0      101     Ali                   OOP     80        40.0
1      102   Ahmad              Database     87        43.5
2      103    Umer  Software Engineering     67        33.5
3      104  Zubair                    OS     56        28.0
4      105  Tayyab            Programing     92        46.0

In [49]:
df_student[df_student['Percentage'] > 40]

   Roll_no    Name     Subject  Marks  Percentage
1      102   Ahmad    Database     87        43.5
4      105  Tayyab  Programing     92        46.0

In [50]:
df_student[df_student['Percentage'] > 40].loc[:, ['Roll_no', 'Name']]

   Roll_no    Name
1      102   Ahmad
4      105  Tayyab

In [ ]:
pd.read_